import {useEffect,useMemo,useRef,useState} from "react";
import {api,normalizeAnalysis,depthPercent} from "../services/api";
import {Upload,FileSpreadsheet,CheckCircle2,Loader2,Download,Plus,Activity,ShieldCheck,ChevronRight} from "lucide-react";
import LightCurveChart from "../components/analysis/LightCurveChart";
import {downloadAnalysisReport} from "../services/report";
import PhaseFoldedChart from "../components/analysis/PhaseFoldedChart";

const API=api.base;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function normalizeFlux(data){if(!data.length)return[];const s=data.map(x=>x.flux).sort((a,b)=>a-b),m=s[Math.floor(s.length/2)]||1;return data.map(x=>({time:x.time,flux:x.flux/m}))}
function parseCSV(text){const lines=text.trim().split(/\r?\n/);if(lines.length<2)throw Error("The CSV file does not contain enough data.");const h=lines[0].split(",").map(x=>x.trim().toLowerCase()),ti=h.indexOf("time"),fi=h.indexOf("flux");if(ti<0||fi<0)throw Error("CSV must contain 'time' and 'flux' columns.");return lines.slice(1).map(l=>{const v=l.split(",");return{time:n(v[ti]),flux:n(v[fi])}}).filter(x=>Number.isFinite(x.time)&&Number.isFinite(x.flux))}
function phase(raw){return(raw||[]).map(p=>Array.isArray(p)?{phase:n(p[0]),flux:n(p[1])}:{phase:n(p?.phase??p?.x),flux:n(p?.flux??p?.normalized_flux??p?.y)}).filter(x=>Number.isFinite(x.phase)&&Number.isFinite(x.flux))}
function transit(raw){if(Array.isArray(raw))return raw.map(x=>typeof x==="number"?{time:x}:x);if(typeof raw==="string")try{return transit(JSON.parse(raw))}catch{return[]}return[]}
export default function Analyze({analysisId}){
 const input=useRef();const[file,setFile]=useState(null);const[chart,setChart]=useState([]);const[result,setResult]=useState(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{if(!analysisId)return;(async()=>{try{setLoading(true);const d=normalizeAnalysis(await api.analysis(analysisId));setResult(d);setFile({name:d.filename||"Stored analysis",size:0});setChart(normalizeFlux(d.lightCurve));}catch(e){setError(e.message)}finally{setLoading(false)}})()},[analysisId]);
 const ca=result?.candidate_analysis||{},ml=result?.ml_prediction||{};let conf=n(ml.confidence);if(conf<=1)conf*=100;const score=n(ca.candidate_score);const candidate=ml.prediction==="planetary_candidate";const phaseData=result?.phaseFoldedCurve||[];const transits=result?.transits||[];
 const onFile=async f=>{if(!f)return;setError("");setResult(null);setFile(f);try{const p=parseCSV(await f.text());setChart(normalizeFlux(p.length>1200?p.filter((_,i)=>i%Math.ceil(p.length/1200)===0):p))}catch(e){setError(e.message);setFile(null);setChart([])}};
 const run=async()=>{if(!file||!file.size){setError("Please upload a CSV file first.");return}try{setLoading(true);setError("");const d=normalizeAnalysis(await api.analyze(file));setResult(d);setChart(normalizeFlux(d.lightCurve));}catch(e){setError(e.message||"The backend analysis failed.")}finally{setLoading(false)}};
 const clear=()=>{setFile(null);setChart([]);setResult(null);setError("")};
 return <div className="mx-auto max-w-[1320px] px-5 py-5 xl:px-6">
  <header className="mb-4 flex items-start justify-between"><div><h1 className="text-[24px] font-semibold text-white">Analyze Light Curve</h1><p className="mt-1 text-[12px] text-slate-400">Upload a stellar light curve and let Drishti analyze it for potential exoplanet signals.</p></div><div className="flex items-center gap-2">{result&&<span className="flex items-center gap-1 rounded-md bg-emerald-500/[.07] px-3 py-2 text-[9px] text-emerald-400">◇ Analysis Complete</span>}{result&&<span className="text-[9px] text-slate-500">ID: #{result.id||analysisId||"—"}</span>}<button disabled={!result} onClick={()=>downloadAnalysisReport(result)} className="flex items-center gap-2 rounded-md border border-violet-500/40 px-3 py-2 text-[10px] text-violet-300 disabled:cursor-not-allowed disabled:opacity-40"><Download size={13}/>Download Report</button><button onClick={clear} className="flex items-center gap-2 rounded-md bg-violet-600 px-3 py-2 text-[10px] font-semibold text-white"><Plus size={13}/>New Analysis</button></div></header>
  {error&&<div className="mb-3 rounded-lg border border-red-400/20 bg-red-500/[.05] p-3 text-xs text-red-300">{error}</div>}
  <div className="grid gap-3 xl:grid-cols-[220px_minmax(0,1fr)_210px]">
   <aside className="space-y-2">
    <div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onFile(e.dataTransfer.files?.[0])}} onClick={()=>input.current?.click()} className="flex h-[144px] cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed border-violet-400/40 bg-[#050c19] text-center"><Upload size={30} className="text-violet-400"/><p className="mt-3 text-[11px] text-slate-300">Drag & drop CSV file here</p><p className="text-[10px] text-slate-600">or</p><span className="mt-2 rounded-md bg-violet-600 px-4 py-2 text-[10px] font-semibold text-white">Choose File</span><input ref={input} type="file" accept=".csv,text/csv" hidden onChange={e=>onFile(e.target.files?.[0])}/></div>
    {file&&<div className="rounded-lg border border-white/[.08] bg-[#071020] p-3"><div className="flex items-center gap-2"><FileSpreadsheet size={17} className="text-violet-400"/><div className="min-w-0"><p className="truncate text-[10px] text-slate-200">{file.name}</p><p className="mt-1 text-[9px] text-slate-600">{file.size?`${(file.size/1024/1024).toFixed(1)} MB`:"Stored analysis"}</p></div><CheckCircle2 size={14} className="ml-auto text-emerald-400"/></div></div>}
    <div className="rounded-lg border border-white/[.07] bg-[#050c19] p-3">{["File Uploaded","Preprocessing","BLS Detection","Feature Extraction","AI Classification"].map((x,i)=><div key={x} className="flex items-center gap-2 py-2 text-[10px]"><span className={`flex h-4 w-4 items-center justify-center rounded-full ${result||i===0?"bg-emerald-500 text-slate-950":"bg-slate-700 text-slate-400"}`}>{result||i===0?"✓":i+1}</span><span className={result||i===0?"text-slate-300":"text-slate-600"}>{x}</span><span className="ml-auto text-[9px] text-emerald-400">{result||i===0?"Completed":""}</span></div>)}</div>
    <button onClick={run} disabled={!file||loading||!file.size} className="flex w-full items-center justify-center gap-2 rounded-lg bg-violet-600 py-2.5 text-[10px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{loading?<Loader2 size={14} className="animate-spin"/>:<Activity size={14}/>}Analyze Light Curve</button>
   </aside>

   <main className="space-y-2">
    <div className="grid gap-2 xl:grid-cols-2">
      <Panel title="Raw Light Curve" legend={["Detrended Flux","Detected Transits"]}><div className="h-[270px]"><LightCurveChart data={chart} detectedTransits={transits}/></div></Panel>
      <Panel title={`Phase Folded ${ca.period?`(P = ${n(ca.period_days).toFixed(3)} days)`:""}`} legend={["Folded Flux","Binned Flux"]}><div className="h-[270px]"><PhaseFoldedChart data={phaseData} periodDays={n(ca.period_days)} transitDurationDays={n(ca.transit_duration_days)}/></div></Panel>
    </div>
    <div className="grid grid-cols-8 gap-1.5">{[
      ["Period",ca.period_days,"days","blue"],["Transit Depth",depthPercent(ca.transit_depth),"%","violet"],["Transit Duration",ca.transit_duration_days?ca.transit_duration_days*24:0,"hours","green"],["BLS Power",ca.bls_power,"","amber"],["BLS SNR",ca.bls_snr,"","red"],["# of Transits",ca.number_of_transits,"","white"],["Odd-Even Diff.",ca.odd_even_difference,"","blue"],["Periodicity Score",ca.periodicity_score,"","green"]
    ].map(([l,v,u,c])=><div key={l} className="rounded-lg border border-white/[.07] bg-[#050c19] px-2.5 py-2.5"><p className="text-[8px] text-slate-500">{l}</p><p className={`mt-1 text-[15px] font-medium ${c==="blue"?"text-sky-400":c==="violet"?"text-violet-400":c==="green"?"text-emerald-400":c==="amber"?"text-amber-400":c==="red"?"text-rose-400":"text-slate-200"}`}>{v===undefined||v===null||!Number.isFinite(Number(v))?"—":Number(v).toFixed(c==="green"&&l==="Periodicity Score"?2:3)} <span className="text-[9px] text-slate-600">{u}</span></p></div>)}</div>
    <div className="grid gap-2 xl:grid-cols-2">
      <div className="dr-card rounded-xl p-4"><h2 className="text-[14px] font-semibold text-white">Detected Transits</h2><table className="mt-3 w-full"><thead><tr><th className="table-head">#</th><th className="table-head">Transit Time (BJD - 2457000)</th><th className="table-head">Depth (%)</th></tr></thead><tbody>{transits.slice(0,7).map((t,i)=><tr key={i} className="border-t border-white/[.05]"><td className="px-3 py-2 text-[10px] text-slate-400">{i+1}</td><td className="px-3 py-2 text-[10px] text-slate-300">{n(t.time).toFixed(3)}</td><td className="px-3 py-2 text-[10px] text-slate-300">{depthPercent(t.depth).toFixed(3)}</td></tr>)}</tbody></table></div>
      <div className="dr-card rounded-xl p-4"><h2 className="text-[14px] font-semibold text-white">AI Prediction</h2><div className="mt-3 grid grid-cols-[145px_1fr] gap-5"><div className="flex h-[145px] w-[145px] items-center justify-center rounded-full" style={{background:`conic-gradient(#22c55e 0 ${conf}%,#16243b ${conf}% 100%)`}}><div className="flex h-[112px] w-[112px] flex-col items-center justify-center rounded-full bg-[#071020]"><span className="text-[25px] font-semibold text-white">{conf.toFixed(1)}%</span><span className="mt-1 text-[10px] text-emerald-400">{candidate?"Planetary Candidate":"Needs Review"}</span></div></div><div className="text-[10px]"><p className="text-[13px] font-semibold text-slate-200">{candidate?"High probability of a planetary transit signal.":"Signal requires further investigation."}</p><p className="mt-3 leading-5 text-slate-500">The light curve shows periodicity with consistent transit depth and shape.</p><div className="mt-3 space-y-2"><Row k="Classification" v={candidate?"Planetary Candidate":"Needs Review"}/><Row k="Model Confidence" v={`${conf.toFixed(1)}%`}/><Row k="Probability (Candidate)" v={n(ml.candidate_probability,.0).toFixed(3)}/><Row k="Probability (Non-candidate)" v={n(ml.non_candidate_probability,.0).toFixed(3)}/></div></div></div></div>
    </div>
   </main>

   <aside className="dr-card rounded-xl p-4"><h2 className="text-[14px] font-semibold text-white">Candidate Score</h2><div className="mx-auto mt-5 flex h-[145px] w-[145px] items-center justify-center rounded-full" style={{background:`conic-gradient(#a855f7 0 ${score}%,#182338 ${score}% 100%)`}}><div className="flex h-[115px] w-[115px] flex-col items-center justify-center rounded-full bg-[#071020]"><span className="text-[25px] font-semibold text-white">{score.toFixed(1)}</span><span className="text-[10px] text-slate-500">/100</span></div></div><p className="mt-2 text-center text-[10px] text-emerald-400">{score>=70?"High Priority":"Review"}</p><div className="my-5 h-px bg-white/[.07]"/><p className="text-[11px] font-medium text-slate-300">Score Breakdown</p>{[["Transit Depth",ca.transit_depth,20],["BLS SNR",ca.bls_snr,20],["Periodicity",ca.periodicity_score,20],["Odd-Even Consistency",1-n(ca.odd_even_difference),20],["Transit Count",ca.number_of_transits,20]].map(([k,v,max])=><div key={k} className="mt-4"><div className="flex justify-between text-[9px]"><span className="text-slate-400">{k}</span><span className="text-slate-300">{n(v).toFixed(2)} / {max}</span></div><div className="mt-1 h-1.5 rounded-full bg-slate-800"><div className="h-full rounded-full bg-violet-500" style={{width:`${Math.min(100,(n(v)/max)*100)}%`}}/></div></div>)}<div className="my-5 h-px bg-white/[.07]"/><p className="text-[11px] font-medium text-slate-300">Key Features</p><ul className="mt-3 space-y-3 text-[10px] text-slate-400"><li>◉ Strong periodic signal</li><li>◉ High SNR ({n(ca.bls_snr).toFixed(2)})</li><li>◉ Consistent transit depth</li><li>◉ Low odd-even difference</li><li>◉ {n(ca.number_of_transits)} predicted transits</li></ul></aside>
  </div>
 </div>
}
function Panel({title,legend,children}){return <div className="rounded-lg border border-white/[.08] bg-[#050c19] p-2.5"><div className="mb-1 flex items-center gap-4"><h3 className="text-[12px] font-medium text-white">{title}</h3>{legend.map((x,i)=><span key={x} className="flex items-center gap-1 text-[8px] text-slate-500"><i className={`h-1.5 w-1.5 rounded-full ${i?"bg-rose-400":"bg-blue-500"}`}/>{x}</span>)}</div>{children}</div>}
function Row({k,v}){return <div className="flex justify-between border-b border-white/[.04] pb-1.5"><span className="text-slate-500">{k}</span><span className="text-slate-300">{v}</span></div>}
