import {useEffect,useMemo,useState} from "react";
import {Search,SlidersHorizontal,ChevronRight,Download,CalendarDays} from "lucide-react";

const API=import.meta.env.VITE_API_URL||"http://localhost:8000/api";
const n=v=>Number.isFinite(Number(v))?Number(v):0;
function fmt(item,index){const a=item.candidate_analysis||{},m=item.ml_prediction||{};let c=n(m.confidence);if(c<=1)c*=100;const f=item.filename||"Unknown";return{id:item.id,rank:index+1,filename:f,target:f.replace(/\.[^/.]+$/,"").replace(/_/g," "),period:n(a.period_days),depth:n(a.transit_depth),snr:n(a.bls_snr),score:n(a.candidate_score),confidence:c,created:item.created_at,priority:c>=80?"HIGH":c>=65?"MEDIUM":"LOW"}}
export default function Candidates({setPage,setSelectedAnalysisId}){
 const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);const r=await fetch(`${API}/candidates`);if(!r.ok)throw Error(`Server returned ${r.status}`);const d=await r.json();const unique=[...new Map((d.candidates||[]).map(x=>[x.filename,x])).values()];setRows(unique.map(fmt))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?rows.filter(x=>x.target.toLowerCase().includes(q)||x.filename.toLowerCase().includes(q)):rows},[rows,search]);
 const high=rows.filter(x=>x.priority==="HIGH").length,med=rows.filter(x=>x.priority==="MEDIUM").length,low=rows.filter(x=>x.priority==="LOW").length,total=rows.length||1;
 const pctHigh=high/total*100,pctMed=med/total*100;
 const exportCSV=()=>{const h=["Rank","Target/File","Period(days)","Depth(%)","SNR","Score","Confidence","Priority","Analyzed At"];const b=rows.map(x=>[x.rank,x.filename,x.period,x.depth,x.snr,x.score,x.confidence,x.priority,x.created]);const csv=[h,...b].map(r=>r.join(",")).join("\\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="drishti-candidates.csv";a.click()};
 return <div className="mx-auto max-w-[1280px] px-5 py-6 xl:px-7">
  <header className="mb-5 flex items-start justify-between"><div><h1 className="text-[28px] font-semibold text-white">Top Planetary Candidates</h1><p className="mt-1 text-[14px] text-slate-400">Explore and prioritize the most promising exoplanet candidates detected by Drishti.</p></div><div className="flex items-center gap-2"><button className="flex items-center gap-2 rounded-lg border border-white/[.08] bg-[#07101f] px-3.5 py-2.5 text-[11px] text-slate-300"><CalendarDays size={14}/>Last 30 Days<ChevronRight size={13} className="rotate-90"/></button><button onClick={exportCSV} className="flex items-center gap-2 rounded-lg bg-violet-600 px-3.5 py-2.5 text-[11px] font-semibold text-white"><Download size={13}/>Export CSV</button></div></header>
  <section className="dr-card rounded-xl p-3">
   <div className="flex flex-wrap items-center gap-2 pb-3"><Select label="All Priorities"/><Select label="All Scores"/><Select label="All Status"/><div className="dr-input flex h-9 w-[230px] items-center gap-2 rounded-lg px-3"><Search size={14} className="text-slate-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by target or filename..." className="w-full bg-transparent text-[11px] text-slate-300 outline-none placeholder:text-slate-600"/></div><button className="ml-auto flex items-center gap-2 rounded-lg border border-white/[.08] px-3 py-2 text-[11px] text-slate-400"><SlidersHorizontal size={13}/>Sort by: Confidence<ChevronRight size={12} className="rotate-90"/></button></div>
   {error&&<div className="mb-3 rounded-lg bg-red-500/10 p-3 text-xs text-red-300">{error}</div>}
   <div className="overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr><th className="table-head">Rank</th><th className="table-head">Target / File</th><th className="table-head">Period (days)</th><th className="table-head">Depth (%)</th><th className="table-head">SNR</th><th className="table-head">Score</th><th className="table-head">Confidence</th><th className="table-head">Priority</th><th className="table-head">Analyzed At</th><th className="table-head"/></tr></thead><tbody>
    {loading?<tr><td colSpan="10" className="p-16 text-center text-xs text-slate-600">Loading candidate observations...</td></tr>:filtered.map((x,i)=><tr key={x.id||x.filename} className="border-t border-white/[.05] hover:bg-white/[.018]">
      <td className="px-3 py-3"><span className={`inline-flex h-6 w-6 items-center justify-center rounded-full text-[10px] ${i===0?"bg-amber-400 text-slate-950":i===1?"bg-slate-300 text-slate-900":i===2?"bg-orange-500/80 text-white":"text-slate-400"}`}>{i+1}</span></td>
      <td className="px-3 py-3"><p className="text-[12px] font-medium text-slate-200">{x.filename}</p><p className="mt-0.5 text-[10px] text-slate-600">{x.target.replace("lightcurve","").trim()}</p></td>
      <td className="px-3 py-3 text-[12px] text-slate-300">{x.period.toFixed(3)}</td><td className="px-3 py-3 text-[12px] text-slate-300">{x.depth.toFixed(3)}</td><td className="px-3 py-3 text-[12px] text-slate-300">{x.snr.toFixed(2)}</td><td className="px-3 py-3 text-[12px] font-semibold text-rose-400">{x.score?x.score.toFixed(1):"—"}</td>
      <td className="px-3 py-3"><div className="w-[110px]"><div className="mb-1 text-[11px] text-slate-300">{x.confidence.toFixed(1)}%</div><div className="h-1.5 rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-400" style={{width:`${Math.min(x.confidence,100)}%`}}/></div></div></td>
      <td className="px-3 py-3"><span className={`rounded-md px-2 py-1 text-[9px] font-semibold ${x.priority==="HIGH"?"bg-emerald-500/10 text-emerald-300":x.priority==="MEDIUM"?"bg-amber-500/10 text-amber-300":"bg-blue-500/10 text-blue-300"}`}>{x.priority}</span></td>
      <td className="px-3 py-3 text-[10px] text-slate-500">{x.created?new Date(x.created).toLocaleString():"—"}</td>
      <td className="px-3 py-3"><button onClick={()=>{setSelectedAnalysisId(x.id);setPage("analyze")}} className="flex h-7 w-7 items-center justify-center rounded-md text-slate-600 hover:bg-violet-500/10 hover:text-violet-300"><ChevronRight size={14}/></button></td>
    </tr>)}
   </tbody></table></div>
  </section>
  <section className="dr-card mt-3 grid gap-6 rounded-xl p-5 xl:grid-cols-[1fr_285px]">
   <div><h2 className="text-[16px] font-semibold text-white">Candidate Summary</h2><div className="mt-4 grid grid-cols-[210px_1fr] items-center gap-8"><div className="relative mx-auto flex h-[185px] w-[185px] items-center justify-center rounded-full" style={{background:`conic-gradient(#22c55e 0 ${pctHigh}%,#f59e0b ${pctHigh}% ${pctHigh+pctMed}%,#3b82f6 ${pctHigh+pctMed}% 100%)`}}><div className="flex h-[135px] w-[135px] flex-col items-center justify-center rounded-full bg-[#071020]"><span className="text-[28px] font-semibold text-white">{rows.length}</span><span className="text-[10px] text-slate-500">Total</span></div></div><div className="space-y-4 text-[11px]"><Legend c="bg-emerald-400" label="High Priority" n={high} total={rows.length}/><Legend c="bg-amber-400" label="Medium Priority" n={med} total={rows.length}/><Legend c="bg-blue-400" label="Low Priority" n={low} total={rows.length}/></div></div></div>
   <div className="rounded-xl border border-violet-400/10 bg-violet-500/[.04] p-4"><p className="text-[12px] font-semibold text-violet-300">Quick Insight</p><p className="mt-2 text-[11px] leading-5 text-slate-500">{high} high-priority candidates detected in the last 30 days. These are the most promising signals worthy of further astronomical investigation.</p></div>
  </section>
 </div>
}
function Select({label}){return <button className="flex h-9 items-center gap-5 rounded-lg border border-white/[.08] bg-[#07101f] px-3 text-[11px] text-slate-400">{label}<ChevronRight size={12} className="rotate-90"/></button>}
function Legend({c,label,n,total}){return <div className="flex items-center justify-between gap-6"><span className="flex items-center gap-2 text-slate-400"><i className={`h-2 w-2 rounded-full ${c}`}/>{label}</span><span className="text-slate-300">{n} <span className="text-slate-600">({total?((n/total)*100).toFixed(1):"0.0"}%)</span></span></div>}
